### ISSUE TITLE
Garlic missing ,

### ISSUE THREAD

**Issue by Szara-ManOfHonor** [chaosvolt/CDDA_Nonperishable_Overhaul#1]
The closing } for garlic at line 600 in overrides.json is missing a ,

**Comment by chaosvolt** [comment]
Ack. This is what happens when you rush things, sorry about that.

Fixed by https://github.com/chaosvolt/CDDA_Nonperishable_Overhaul/commit/bf16b6e82e488545efb57a8a035887e4f69760b7
