### ISSUE TITLE
Problems with json format in build 9996

### ISSUE THREAD

**Issue by HeartwawyHorror** [chaosvolt/CDDA_Nonperishable_Overhaul#2]
![image](https://user-images.githubusercontent.com/51540578/70760985-90443b00-1d19-11ea-9c39-357401dd290d.png)

![image](https://user-images.githubusercontent.com/51540578/70760992-9afed000-1d19-11ea-8cdb-8f17a89465cc.png)

I loaded the game up and I think both have to do with the man meats stuff.

**Comment by chaosvolt** [comment]
Oh right, the meat changes! Thanks for reminding me.

**Comment by chaosvolt** [comment]
And that second one is an MST Extra error, in fact.
