### ISSUE TITLE
Fail to visit name_plural in JsonObject

### ISSUE THREAD

**Issue by Lamandus** [chaosvolt/CDDA_Nonperishable_Overhaul#3]
in the newest experimental "name_plural" doesn't seem to work anymore. So it probably should be changed accordingly.

**Comment by chaosvolt** [comment]
Ah, guess string-based names are being more strictly enforced it seems. Will work on that in a bit.

**Comment by Lamandus** [comment]
I can do it myself and make a pull request, if you don't mind.

**Comment by chaosvolt** [comment]
I've already gotten partway through it, actually. No worries, will have it committed in a bit.

**Comment by Lamandus** [comment]
hehe alright. I was already at "id": "mintpatties". Thank you

**Comment by chaosvolt** [comment]
In fact I'm fairly certain names and descriptions aren't actually needed for copy-from overrides, I'm gonna test that while I'm at it.
