### ISSUE TITLE
JSON contains circular dependency (0.F-3)

### ISSUE THREAD

**Issue by Outcognito** [chaosvolt/CDDA_Nonperishable_Overhaul#6]
![image](https://user-images.githubusercontent.com/31615562/167300929-295f178c-7b0c-4a0b-9997-daaacbafdc93.png)
![image](https://user-images.githubusercontent.com/31615562/167300944-21564f0c-57c3-469c-9418-5b0348bde86e.png)
![image](https://user-images.githubusercontent.com/31615562/167300952-80e99aac-27b8-46df-9c9a-748bddc13833.png)
![image](https://user-images.githubusercontent.com/31615562/167300960-16a0375d-2b26-4da5-aedc-261cf2703afd.png)
![image](https://user-images.githubusercontent.com/31615562/167300970-82108ca0-11a1-42ee-b077-d7a81c6da748.png)
![image](https://user-images.githubusercontent.com/31615562/167300978-f84cffbb-f5b8-401c-9803-821d8486ebd5.png)
![image](https://user-images.githubusercontent.com/31615562/167300990-cb0f1dd2-46e2-4c3e-b128-0ffaa4d13373.png)
![image](https://user-images.githubusercontent.com/31615562/167301001-40c16290-1368-4ad4-afea-7210d4884a91.png)
[debug.log](https://github.com/chaosvolt/CDDA_Nonperishable_Overhaul/files/8647156/debug.log)

**Comment by Outcognito** [comment]
[debug.log](https://github.com/chaosvolt/CDDA_Nonperishable_Overhaul/files/8647162/debug.log)
Cleaner log

**Comment by chaosvolt** [comment]
This mod also still needs a separate 0.F version set up.
